name       : libwhich
version    : 1.1.0
release    : 2
source     :
    - https://github.com/vtjnash/libwhich/archive/refs/tags/v1.1.0.tar.gz : f1c30bf7396859ad437a5db74e9e328fb4b4e1379457121e28a3524b1e3a0b3f
homepage   : https://github.com/vtjnash/libwhich
license    : MIT
component  : programming.library
summary    : Like which but for dynamic libraries
description: |
    Like which, for dynamic libraries. Also a bit like ldd.
build      : |
    %make
install    : |
    install -Dm00755 libwhich $installdir/usr/bin/libwhich
